// <auto-generated />
namespace Dipayan_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class createnewdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createnewdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202004120654149_createnewdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
